name: strelka-daily-builder
on:
  push
#  schedule:
#    - cron: '0 2 * * *'
jobs:
  strelka:
    name: Strelka
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Builds Strelka
        run: docker-compose -f build/docker-compose.yaml build
        
