name: pr-actions
on: [pull_request]

jobs:
  backend-strelka-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:

          python-version: '3.x'

          architecture: 'x64'
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install --no-install-recommends -qq automake \
            build-essential \
            libfuzzy-dev \
            gcc \
            git \
            libarchive-dev \
            libmagic-dev \
            libssl-dev \
            libzbar0 \
            libgl1 \
            python3-setuptools \
            libgmp-dev \
            libpcap-dev \
            libbz2-dev \
            libgomp1 \
            python3-dev \
            python3-wheel \
            mupdf-tools \
            mupdf \
            libglu1-mesa \
            libtool \
            pkg-config \
            swig \
            tesseract-ocr 
          python -m pip install --upgrade pip
          pip install validators setuptools --upgrade
          pip install --no-cache-dir -r src/python/requirements.txt
      - name: Test with pytest
        run: |
          pytest
      

